#ifndef ZACK_LOG_HH
#define ZACK_LOG_HH

#include "soil/Log.hh"

#define ZACK_LOG_INIT(x) SOIL_LOG_INIT(x)

#define ZACK_TRACE SOIL_TRACE
#define ZACK_DEBUG SOIL_DEBUG
#define ZACK_INFO  SOIL_INFO
#define ZACK_WARNING SOIL_WARNING
#define ZACK_ERROR SOIL_ERROR
#define ZACK_FATAL SOIL_FATAL
#define ZACK_PDU SOIL_PDU
#define ZACK_CUSTOM SOIL_CUSTOM


#endif

